# Liulishuo Game Project
#

stages:
    - lint
    - test
    - build
    - deploy

variables:
    LC_ALL: 'en_US.UTF-8'
    LANG: 'en_US.UTF-8'
    GIT_SUBMODULE_STRATEGY: recursive
    GAME_VERSION: '1.0.0'
    GAME_NAME: 'leohome'
    GAME_ARCHIVE_PATH: 'git@git.llsapp.com:sprout/game/leohome-archive.git'
    BUNDLE_PATH: 'build/${GAME_NAME}'
    IOS_BETA_BRANCH: 'feature/add_leohome'
    ANDROID_BETA_BRANCH: 'feature1.7/addLeoHomeEntry'

before_script:
    - npm ci

Lint:
    script:
        - npm run validate
    type: lint
    only:
        - /^release/*/
        - /^feature/*/
        - /^fix/*/
    tags:
        - cocos

Test:
    script:
        - npm run test
    type: test
    only:
        - /^release/*/
        - /^feature/*/
        - /^fix/*/
    tags:
        - cocos

Beta:
    script:
        - ci/scripts/extract-version-info.sh
        - npm run compress
        - ci/scripts/archive-game.sh
    cache:
        key: '${GAME_NAME}-beta'
        paths:
            - build/
            - packages/
    artifacts:
        paths:
            - build/$GAME_NAME
        expire_in: 1 week
    type: build
    when: manual
    allow_failure: false
    only:
        - /^release/*/
        - develop
        - /^feature/*/
    except:
        - schedules
    tags:
        - cocos

Release:
    script:
        - ci/scripts/extract-version-info.sh
        - npm run compress
        - ci/scripts/archive-game.sh --release
        - ci/scripts/upload-game-iOS.sh --release
        - ci/scripts/upload-game-Android.sh --release
    cache:
        key: '${GAME_NAME}-release'
        paths:
            - build/
            - packages/
    type: build
    when: manual
    only:
        - /^release/*/
        - /^hotfix/*/
    tags:
        - cocos

DailyBeta:
    extends: Beta
    when: always
    only:
        - schedules
    except: []

.DeployBeta:
    type: deploy
    dependencies:
        - Beta
        - DailyBeta
    only:
        - /^release/*/
        - develop
        - /^feature/*/
    tags:
        - cocos

iOSBeta:
    extends: .DeployBeta
    script:
        - ci/scripts/upload-game-iOS.sh

AndroidBeta:
    extends: .DeployBeta
    script:
        - ci/scripts/upload-game-Android.sh

